title: Dev Guides
description: Guias de desenvolvimento e ferramentas para desenvolvedores
baseurl: "/dev-guides"
url: "https://varantes.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Jekyll configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tagging

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Guias
    url: /guides/
  - title: Claude Code WSL
    url: /docs/claude-code-wsl/

# Site settings
lang: pt-BR
author: Valdemar Arantes Neto

# GitHub Pages settings
github_username: varantes
repository: dev-guides

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - .idea
  - docs/desenvolvimento/
  - screenshots/

# Include files
include:
  - _pages

# Sass configuration
sass:
  style: compressed

# Pagination
paginate: 10
paginate_path: "/page:num/"

# SEO settings
twitter:
  username: seu_twitter
  card: summary

social:
  name: Valdemar Arantes Neto
  links:
    - https://github.com/varantes

# Tags configuration
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# SEO and LLM optimization
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
      sitemap: true
      
# Structured data
schema:
  type: TechnicalArticle
  publisher: "Dev Guides"